config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'office_hours#index'

  resources :office_hours

  # Building and Department resources will have an autocomplete
  # route for AJAX get requests.
  get '/buildings/autocomplete', to: 'buildings#autocomplete'
  get '/departments/autocomplete', to: 'departments#autocomplete'

  namespace :admin do
    resources :departments, :office_hours, :buildings
    resources :members do
      collection { get :upload }
      collection { post :import }
    end
  end
end

app/models/member.rb
# Each faculty member is an instance of the Member class. Members must have a
# firstname and lastname. They can also have an email, have_many office_hours,
# and belong_to one building and one department.
class Member < ActiveRecord::Base
  searchkick callbacks: :async
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :firstname, :lastname, presence: true, length: { maximum: 25 }
  validates :email,
            format: { with: VALID_EMAIL_REGEX },
            allow_nil: true,
            uniqueness: { case_sensitive: false }
  belongs_to :department
  belongs_to :building
  has_many :office_hours, dependent: :destroy

  delegate :name, to: :department, prefix: true
  delegate :fullname, to: :building, prefix: true, allow_nil: true

  def search_data
    attributes.merge(
      department_name: department_name,
      building_fullname: building_fullname
    )
  end

  # Member.searching is used to sort tables of members by selected columns and
  # allow the user to change the sort direction (ascending or descending). it
  # also takes a page argument in order to preserve the current page when
  # resorting tables containing multiple pages of entries.
  def self.searching(query, sort_column, sort_direction, page)
    # if a non-empty query string is provided, then preserve that query
    if query
      search query, order: { sort_column => sort_direction },
                    page: page, per_page: 25
    # if an empty query is provided, return all records
    else
      search '*'
    end
  end

  # Returns the member's fullname
  def fullname
    firstname + ' ' + lastname
  end

  # hours_on_day takes an integer encoding of a weekday and returns all of the
  # office hours that occur on that day. Sunday is 0.
  def hours_on_day(day)
    office_hours.where(day: day)
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :redirect_non_admin
  def index
    redirect_non_admin
    @members = Member.includes(:department, :building, :office_hours)
                     .searching(search_term, sort_column, sort_direction, page)
    @member = Member.new
  end

  def upload
  end

  def import
    importer = ImportMembersFromCsv.new(params[:file])
    importer.import
    redirect_to admin_members_path, notice: 'Members Imported.'
  end

  def edit
    @current_member = Member.find(params[:id])
    respond_to :js
  end

  def new
    @member = Member.new
    respond_to :js, :html
  end

  def create
    @member = Member.create(member_params)
    respond_to :js, :html, :xml
  end

  def update
    flash[:notice] = 'Member was successfully updated.'
    @member = Member.find(params[:id])
    @member.update(admin_params)
    respond_to :js, :html
  end

  def destroy
    Member.delete(params[:id])
    respond_to do |f|
      f.js
    end
    redirect_to admin_members_path
  end

  private

  def member_params
    params.require(:member).permit(:firstname, :lastname, :building_id,
                                   :door_number, :department_id, :email)
  end

  def redirect_non_admin
    redirect_to root_path unless current_user.role == 1
  end

  def search_term
    params[:search].blank? ? '*' : params[:search]
  end

  def page
    params[:page] || 1
  end

  def sort_column
    permitted_opts = %w(firstname lastname building_fullname department_name)
    if permitted_opts.include?(params[:sort])
      params[:sort]
    else
      'department_name'
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/views/admin/members/_edit.html.erb
<div class='modal-dialog'>
  <div class='modal-content'>
    <div class='modal-header'>
      <h3>Edit Record For <%= @current_member.firstname + ' ' + @current_member.lastname %></h3>
    </div>
    <%= form_for [:admin, @current_member], remote: true, html: {style: 'display:inline;'} do |f|  %>
      <div class='modal-body'>
        <div class='form-group'>
          <%= f.label :firstname, class: 'control-label' %>
          <%= f.text_field :firstname, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :lastname, class: 'control-group' %>
          <%= f.text_field :lastname, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :email, class: 'control-group' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :department_id, class:'control-group' %>
          <%= f.collection_select :department_id, Department.all, :id, :name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :building_id, class: 'control-group' %>
      	  <%= f.collection_select  :building_id, Building.all, :id, :fullname, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :door_number, class: 'control-group' %>
          <%= f.text_field :door_number, class: 'form-control' %>
        </div>
        <div class='modal-footer'>
          <%= f.submit class:'btn btn-primary' %>
          <%= link_to 'Cancel', '#', class: 'btn', data: {dismiss: 'modal'} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/members/_member_table.html.erb
<%= form_tag admin_members_path, method: 'get', class: 'form-inline' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <%= text_field_tag :search, params[:search], placeholder: 'Name, Building, or Department' %>
  <%= submit_tag "Search", class: 'btn btn-primary btn-sm' %>
<% end %>

<br />

<table class='table table-bordered member-table'>
  <tr>
    <th><%= sortable 'firstname', 'First Name' %></th>
    <th><%= sortable 'lastname', 'Last Name' %></th>
    <th><%= sortable 'department_name', 'Department' %></th>
    <th><%= sortable 'building_fullname', 'Office' %></th>
    <th>Email</th>
    <th>Office Hours</th>
    <th>Action</th>
  </tr>
  <% @members.each do |m| %>
  <tr class='member_row'>
    <td><%= m.firstname %></td>
    <td><%= m.lastname %></td>
    <td><%= m.department.name unless m.department.blank? %></td>
    <td><%= m.building.abbrev + " " + m.door_number unless m.building.blank? %></td>
    <td><%= m.email unless m.email.blank? %></td>
    <td>
      <ul>
        <% m.office_hours.each do |h| %>
          <li><%= Date::DAYNAMES[h.day]%>: <%= h.start.strftime('%l:%M') %>-<%= h.stop.strftime('%l:%M%P') %></li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Edit', edit_admin_member_path(m), remote: true %> <%= link_to 'Delete', admin_member_path(m), :method => :delete, remote: true %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @members %>

app/views/admin/members/_new.html.erb
<div class='modal-dialog'>
  <div class='modal-content'>
    <div class='modal-header'>
      <h3>New Member</h3>
    </div>
    <%= form_for [:admin, @member], remote: true, html: {style: 'display:inline;'} do |f| %>
      <div class='modal-body'>
        <ul class='errors'></ul>

        <div class='form-group'>
          <%= f.label :firstname, class: 'control-label' %>
          <%= f.text_field :firstname, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :lastname, class: 'control-label' %>
          <%= f.text_field :lastname, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :email, class: 'control-label' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :department_id, class: 'control-label' %>
          <%= f.collection_select :department_id, Department.all, :id, :name %>
        </div>

        <div class='form-group'>
          <%= f.label :building_id, class: 'control-label' %>
          <%= f.collection_select :building_id, Building.all, :id, :fullname %>
        </div>

        <div class='form-group'>
          <%= f.label :door_number, class: 'control-lable' %>
          <%= f.text_field :door_number, class: 'form-control' %>
        </div>
      </div>
      <div class='modal-footer'>
        <%= f.submit class:'btn btn-primary' %>
        <%= link_to 'Cancel', '#', class: 'btn', data: {dismiss: 'modal'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/members/_save.js.erb
$('ul.errors').html('')
<% if @member.errors.any? %>
  <% @member.errors.full_messages.each do |m| %>
    $('ul.errors').append($('<li />').html('<%= message.html_safe %>'))
  <% end %>
<% else %>
  $('#member-modal').modal('hide')
<% end %>

app/views/admin/members/create.html.erb
<%= render 'save' %>

app/views/admin/members/edit.js.erb
$(document).ready(function(){
  $('#member-modal').html("<%= escape_javascript( render 'edit') %>")
  $('#member-modal').modal('show')
})

app/views/admin/members/index.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <%= link_to 'Add/Update Members From CSV', upload_admin_members_path %>
  </div>
  <div class='col-xs-3'>
    <%= link_to 'New Member', new_admin_member_path, remote: true %>
  </div>
  <div class='col-xs-3'>
    <%= link_to 'New Department', new_admin_department_path, remote: true %>
  </div>
  <div class='col-xs-3'>
    <%= link_to 'New Building', new_admin_building_path, remote: true %>
  </div>
</div>


<br />
<div class='row'>
  <div class='col-xs-12'>
    <%= render 'member_table' %>
  </div>
</div>

<div id="member-modal" class='modal fade'></div>

app/views/admin/members/new.html.erb
<%= form_for [:admin, @member] do |m| %>
  <%= m.text_field :firstname, placeholder: 'First Name' %>
  <%= m.text_field :lastname, placeholder: 'Last Name' %>
  <%= m.collection_select :department_id, Department.all, :id, :name %>
  <%= m.collection_select :building_id, Building.all, :id, :fullname %>
  <%= m.text_field :door_number, placeholder: 'Door Number' %>
  <%= m.submit 'Submit' %>
<% end %>

app/views/admin/members/new.js.erb
$(document).ready(function(){
  $('#member-modal').html("<%= escape_javascript( render 'new') %>")
  $('#member-modal').modal('show')
})

app/views/admin/members/update.html.erb
<%= render 'save' %>

app/views/admin/members/upload.html.erb
  <div class='col-xs-12 bg-primary'>
    Please ensure that your headers include 'firstname', 'lastname', 'department', and 'email'.
  </div>

  <br />
  <br />

  <div class='col-xs-4'>
    <%= form_tag import_admin_members_path, multipart: true, class: 'form-inline' do %>
      <%= file_field_tag :file %>
      <%= submit_tag 'Submit' %>
    <% end %>
  </div>