config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'office_hours#index'

  resources :office_hours

  # Building and Department resources will have an autocomplete
  # route for AJAX get requests.
  get '/buildings/autocomplete', to: 'buildings#autocomplete'
  get '/departments/autocomplete', to: 'departments#autocomplete'

  namespace :admin do
    resources :departments, :office_hours, :buildings
    resources :members do
      collection { get :upload }
      collection { post :import }
    end
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  searchkick callsbacks: :async,
             text_middle: [:name],
             autocomplete: ['name']
  validates :name, :abbrev, presence: true
  has_many :members
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_filter :redirect_non_admin
  def index
    @departments = Department.all
    respond_to :html, :js
  end

  def new
    @department = Department.new
    respond_to :html, :js
  end

  def create
    @department = Department.create(department_params)
    respond_to :html, :js, :xml
  end

  def edit
    @department = Department.find(params[:id])
    respond_to :html, :js
  end

  def update
    @department = Department.find(params[:id])
    @department.update(admin_params)
    respond_to :html, :js
  end

  def destroy
    @department = Department.find(params[:id])
    @department.delete
    redirect_to admin_departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name, :abbrev)
  end

  def redirect_non_admin
    redirect_to root unless current_user.role == 1
  end
end

app/controllers/departments_controller.rb
# Since all of the CRUD actions for departments are being handled in
# Admin::DepartmentsController (as normal users don't have CRUD access), the
# DepartmentsController is very thin.
class DepartmentsController < ApplicationController
  # Responds jsonified array of elasticsearch(searchkick) department results
  # with keys set to 'name' and departmentment names set as values. This action
  # will be called with jQuery in the OfficeHours index view.
  def autocomplete
    render json: Department.search(params[:query], limit: 10).map { |department| { name: department.name } }
  end
end

app/views/admin/departments/_new.html.erb
<div class='modal-dialog'>
  <div class='modal-content'>
    <div class='modal-header'>
      <h3>New Department</h3>
    </div>
    <div class='modal-body'>
      <%= form_for [:admin, @department], remote: true, html: {style: 'display:inline;'} do |d| %>
        <div class='form-group'>
          <%= d.label :name, class: 'control-group' %>
          <%= d.text_field :name, placeholder: 'Full Name', class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= d.label :abbrev, class: 'control-group' %>
          <%= d.text_field :abbrev, placeholder: 'Abbreviation', class: 'form-control' %>
        </div>
        <div class='modal-footer'>
          <%= d.submit 'Create Department', class: 'btn btn-primary' %>
          <%= link_to 'Cancel', '#', class: 'btn', data: {dismiss: 'modal'} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/departments/create.js.erb
$('ul.errors').html('')
<% if @department.errors.any? %>
  <% @department.errors.full_messages.each do |message| %>
  $('ul.errors').append('<li />').html('<%= message.html_safe %>'))
  <% end %>
<% else %>
  $('#member-modal').modal('hide')
<% end %>

app/views/admin/departments/edit.html.erb
<h1>Admin::Departments#edit</h1>
<p>Find me in app/views/admin/departments/edit.html.erb</p>
<%= form_for [:admin, @department] do |d| %>
  <%= d.text_field :name %>
  <%= d.text_field :abbrev %>
  <%= d.submit 'Submit' %>
<% end %>

app/views/admin/departments/index.html.erb
<h1>Departments</h1>
<%= link_to 'Add New Department', new_admin_department_path %>
<table class='table'>
  <tr>
    <th>Department Name</th>
    <th>Department Abbreviation</th>
    <th>Actions</th>
  </tr>
  <% @departments.each do |d| %>
    <tr>
      <td><%= d.name %></td>
      <td><%= d.abbrev %></td>
      <td><%= link_to 'Edit', edit_admin_department_path(d) %> <%= link_to 'Delete', admin_department_path(d), method: 'delete' %></td>
    </tr>
  <% end %>
</table>