config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'office_hours#index'

  resources :office_hours

  # Building and Department resources will have an autocomplete
  # route for AJAX get requests.
  get '/buildings/autocomplete', to: 'buildings#autocomplete'
  get '/departments/autocomplete', to: 'departments#autocomplete'

  namespace :admin do
    resources :departments, :office_hours, :buildings
    resources :members do
      collection { get :upload }
      collection { post :import }
    end
  end
end

app/models/building.rb
# Each building on campus is represented as a building object. Buildings must
# have fullnames, and abbrevs. They have_many members, and have_many
# office_hours through those members. They can also have avatars, which will
# be displayed next to each office hour on the main page so that students can
# more easily locate the buildings.
class Building < ActiveRecord::Base
  # searchkick is a gem that makes it easier to work with elasticsearch.
  # callbacks: :async updates the es index in the background when a record is
  # inserted.
  searchkick callbacks: :async,
             # text_middle will return matches when the query sequence matches
             # any place within the selected fields.
             text_middle: %i(fullname abbrev),
             # autocomplete
             autocomplete: %i(fullname abbrev)

  validates :fullname, :abbrev, presence: true
  has_many :members
  has_many :office_hours, through: :members
  # has_attached_file is a helper provided by paperclip. Each building can have
  # an avatar image.
  has_attached_file :avatar,
                    styles: { thumb: '70x70>' },
                    default_url: ActionController::Base
                      .helpers.asset_path('missing.png')
  validates_attachment :avatar, content_type: { content_type: ['image/jpeg'] }
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < ApplicationController
  before_filter :redirect_non_admin
  def index
    @buildings = Building.all
    respond_to :html, :js
  end

  def show
  end

  def new
    @building = Building.new
    respond_to :html, :js
  end

  def create
    @building = Building.create(building_params)
    respond_to :html, :js, :xml
  end

  def edit
    @building = Building.find(params[:id])
    respond_to :html, :js
  end

  def update
    building = Building.find(params[:id])
    building.update(building_params)
    redirect_to admin_buildings_url && return
    respond_to :html, :js
  end

  def destroy
    building = Building.find(params[:id])
    building.delete
  end

  private

  def building_params
    params.require(:building).permit(:fullname, :abbrev, :avatar)
  end

  def redirect_non_admin
    redirect_to root unless current_user.role == 1
  end
end

app/controllers/buildings_controller.rb
# Since all of the CRUD actions for buildings are being handled in
# Admin::BuildingsController (as normal users don't have CRUD access), the
# BuildingsController is very thin.
class BuildingsController < ApplicationController
  # Responds jsonified array of elasticsearch(searchkick) building results
  # with keys set to 'name' and building names set as values.
  def autocomplete
    render json: Building.search(params[:query], limit: 10).map { |building| { name: building.fullname, abbrev: building.abbrev } }
  end
end

app/views/admin/buildings/_new.html.erb
<div class='modal-dialog'>
  <div class='modal-content'>
    <div class='modal-header'>
      <h3>New Building</h3>
    </div>
    <div class='modal-body'>
      <%= form_for [:admin, @building], remote: true, html: {style: 'format:inline;'} do |f| %>
        <div class='form-group'>
          <%= f.label :fullname, class: 'control-group' %>
          <%= f.text_field :fullname, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :abbrev, class: 'control-group' %>
          <%= f.text_field :abbrev, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :avatar, class: 'control-group' %>
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
        <div class='modal-footer'>
          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to 'Cancel', '#', class: 'btn', data: {dismiss: 'modal'} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/buildings/create.js.erb
$('ul.errors').html('')
<% if @building.errors.any? %>
  <% @building.errors.full_messages.each do |message| %>
    $('ul.errors').append('<li />').html('<%= message.html_safe %>')
  <% end %>
<% else %>

  $('#member-modal').modal('hide')
<% end %>

app/views/admin/buildings/edit.html.erb
<h1>Update The Record for <%= @building.fullname %></h1>
<%= form_for [:admin, @building], html: {style:'format:inline;'} do |b| %>
  <div class='form-group'>
    <%= b.label :fullname, class: 'control-group' %>
    <%= b.text_field :fullname, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= b.label :abbrev, class: 'control-group' %>
    <%= b.text_field :abbrev, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= b.label :avatar, class: 'control-group' %>
    <%= b.file_field :avatar, class: 'form-control' %>
  </div>
  <%= b.submit 'Submit' %>
<% end %>

app/views/admin/buildings/index.html.erb
<div> There are <%= @buildings.count %> buildings on campus </div>
<div> <%= link_to 'Add a Building', new_admin_building_path %></div>
<table class='table'>
  <tr>
    <th>Thumbnail</th>
    <th>Full Name</th>
    <th>Abbreviation</th>
    <th>Actions</th>
  </tr>
  <% @buildings.each do |b| %>
    <tr>
      <td><%= image_tag(b.avatar.url(:thumb)) %></td>
      <td><%= b.fullname %></td>
      <td><%= b.abbrev %></td>
      <td><%= link_to('Edit', edit_admin_building_path(b)) %> <%=link_to('Destroy', admin_building_path(b), method: 'Delete') %></td>
    </tr>
  <% end %>
</table>

app/views/admin/buildings/new.js.erb
$('#member-modal').html('<%= j render "new" %>')
$('#member-modal').modal('show')