config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'office_hours#index'

  resources :office_hours

  # Building and Department resources will have an autocomplete
  # route for AJAX get requests.
  get '/buildings/autocomplete', to: 'buildings#autocomplete'
  get '/departments/autocomplete', to: 'departments#autocomplete'

  namespace :admin do
    resources :departments, :office_hours, :buildings
    resources :members do
      collection { get :upload }
      collection { post :import }
    end
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-default row">
	<div class="col-xs-4 navbar-header">
		<span class="navbar-brand"><%= link_to 'OfficeHours', root_path %></span>
	</div>
	<div class="col-xs-8" id="logout">
    <% if current_user.role == 1 %>
      <%= link_to('Member Dashboard', admin_members_path) %>
      &bull;
      <%= link_to('Department Dashboard', admin_departments_path) %>
      &bull;
      <%= link_to('Building Dashboard', admin_buildings_path) %>
      &bull;
    <% end %>

		<% if user_signed_in? %>
			<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
		<% end %>

	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OfficeHours</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
		<%= render 'layouts/navigation' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OfficeHours</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>